import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Mono } from "@/app/ui/fonts";
import "./globals.css";
import {getServerSession} from "next-auth";
import Link from "next/link";
import Logout from "./logout";

const inter = Inter({ subsets: ["latin"] }); 

export const metadata: Metadata = {
  title: "TimeZen Pomodoro App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={Mono.className}>{children}
        <nav>
          {!!session &&
          <Logout />
          }
          {!session &&
          <Link href="/login">Login</Link>
          }
        </nav>
      </body>
    </html>
  );
}
