import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Mono } from "@/app/ui/fonts";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] }); 

export const metadata: Metadata = {
  title: "TimeZen Pomodoro App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Mono.className}>{children}</body>
    </html>
  );
}
