import type { Metadata } from "next";
import { Mono } from "@/app/ui/fonts";
import "./globals.css";
import {getServerSession} from "next-auth";
import Link from "next/link";
import {Inter} from "@/app/ui/fonts"
 

export const metadata: Metadata = {
  title: "TimeZen Pomodoro App",
  description: "Generated by create next app",
  };

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={Inter.className}>{children}
      </body>
    </html>
  );
}
